/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiuye_speech_Speak */

#ifndef _Included_com_xiuye_speech_Speak
#define _Included_com_xiuye_speech_Speak
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiuye_speech_Speak
 * Method:    coInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiuye_speech_Speak_coInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_xiuye_speech_Speak
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiuye_speech_Speak_speak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiuye_speech_Speak
 * Method:    unCoinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiuye_speech_Speak_coUninitialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
